services:
  - type: web
    name: amirhan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amirhan-db
          property: connectionString

databases:
  - name: amirhan-db
    databaseName: amirhan
    user: amirhan
    plan: free 