services:
  - type: web
    name: amirhan-m
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amirhan-m-db
          property: connectionString

databases:
  - name: amirhan-m-db
    databaseName: amirhan_m
    user: amirhan_m
    plan: free 