services:
  - type: web
    name: amirhan-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amirhan-website-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: amirhan-website-db
    databaseName: amirhan_website
    user: amirhan_website
    plan: free 